{% set name = "md2py" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/md2py-{{ version }}.tar.gz
  sha256: 695c91758c70704c4d0c20612aab023496c32dc70aaf59d6fb2743b5d497f764

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - pytest
    - python {{ python_min }}
    - setuptools
  run:
    - beautifulsoup4
    - markdown
    - python >={{ python_min }}

test:
  imports:
    - md2py
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/alvinwan/md2py
  summary: Utility converting Markdown into Python abstraction.
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
